server:
  port: 9001

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      routes:
      - id: service-usercenter
        uri: lb://SERVICE-USERCENTER
        predicates:
          - Path=/user/**
        filters:
          - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/