server:
  port: 9001

spring:
  application:
    name: service-apigateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      routes:
      - id: service-null
        uri: lb://SERVICE-null
        predicates:
          - Path=/nullerror/**
        filters:
          - StripPrefix=1
      - id: service-user
        uri: lb://SERVICE-USER
        predicates:
          - Path=/user/**
        filters:
          - StripPrefix=1
      - id: service-com
        uri: lb://SERVICE-COM
        predicates:
          - Path=/commodity/**
        filters:
          - StripPrefix=1
      - id: service-order
        uri: lb://SERVICE-ORDER
        predicates:
          - Path=/order/**
        filters:
          - StripPrefix=1
          
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/