#服务器配置
server:
  #端口
  port: 9002

#服务器发现注册配置
eureka:
  client:
    serviceUrl:
      #配置服务中心(可配置多个,用逗号隔开)
      defaultZone: http://localhost:9000/eureka/

#spring配置
spring:
  #应用配置
  application:
    #名称: OAuth2认证授权服务
    name: service-oauth
  #数据库配置
  data:
    mongodb:
      port: 27017
      database: admin

      